# Generated by Django 3.1.7 on 2021-03-17 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mailing', models.BooleanField(blank=True, default=False, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('language', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('birthday', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('phone', models.JSONField(blank=True, default=list, max_length=100, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('social_links', models.JSONField(blank=True, default=list, max_length=1000, null=True)),
                ('citizenship', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('profile_link', models.CharField(blank=True, default='empty', max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('profile_background', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('experience', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('education', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('salary', models.IntegerField(blank=True, default=-1, null=True)),
                ('work_type', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('experience', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.JSONField(blank=True, default=list, max_length=700, null=True)),
                ('bg_header_color', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('leading', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pub_date', models.CharField(blank=True, default='2021-03-17 16:09:14.030261', max_length=200, null=True)),
                ('trailing', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('body', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('tags', models.ManyToManyField(to='main.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mailing', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('profile_background', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('links', models.JSONField(blank=True, default=list, max_length=1000, null=True)),
                ('phone', models.JSONField(blank=True, default=list, max_length=100, null=True)),
                ('profile_link', models.CharField(blank=True, default='empty', max_length=500, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('salary', models.IntegerField(blank=True, default=-1, null=True)),
                ('work_type', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('about', models.TextField(blank=True, default='', null=True)),
                ('bg_header_color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pub_date', models.CharField(blank=True, default='2021-03-17 16:09:14.028270', max_length=200, null=True)),
                ('portfolio', models.JSONField(blank=True, default=list, max_length=500, null=True)),
                ('tags', models.ManyToManyField(to='main.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
