# Generated by Django 3.1.7 on 2021-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210317_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 16:34:06.025925', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.JSONField(blank=True, default=dict, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.JSONField(blank=True, default=dict, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 16:34:06.027918', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.JSONField(blank=True, default=dict, max_length=500, null=True),
        ),
    ]
