# Generated by Django 3.1.7 on 2021-03-17 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210317_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 17, 23, 5, 59, 335173), null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.JSONField(blank=True, default={'lat': '', 'lng': '', 'name': ''}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.JSONField(blank=True, default={'lat': '', 'lng': '', 'name': ''}, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 17, 23, 5, 59, 338165), null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.JSONField(blank=True, default={'lat': '', 'lng': '', 'name': ''}, max_length=500, null=True),
        ),
    ]
