# Generated by Django 3.1.7 on 2021-03-18 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210317_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 18, 22, 3, 9, 918228), null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.JSONField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.JSONField(blank=True, default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 18, 22, 3, 9, 920223), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.JSONField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
