# Generated by Django 3.1.7 on 2021-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210307_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='language',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='social_links',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
    ]
