# Generated by Django 3.1.7 on 2021-03-25 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210318_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 16, 5, 2, 667527), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='leading',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 16, 5, 2, 670491), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trailing',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
