# Generated by Django 3.1.7 on 2021-03-30 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210325_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 0, 25, 46, 676001), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 0, 25, 46, 679993), null=True),
        ),
        migrations.CreateModel(
            name='VacancyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_response', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 0, 25, 46, 682984), null=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_employer', to=settings.AUTH_USER_MODEL)),
                ('vacancy_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vacancy')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_worker', to=settings.AUTH_USER_MODEL)),
                ('worker_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CvResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_response', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 31, 0, 25, 46, 682984), null=True)),
                ('cv_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_employer', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vacancy')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
