# Generated by Django 3.1.7 on 2021-04-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210331_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 16, 33, 51, 457601), null=True),
        ),
        migrations.AlterField(
            model_name='cvresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 16, 33, 51, 467573), null=True),
        ),
        migrations.AlterField(
            model_name='cvresponse',
            name='state',
            field=models.CharField(blank=True, default='sent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 16, 33, 51, 462587), null=True),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 1, 16, 33, 51, 466576), null=True),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='state',
            field=models.CharField(blank=True, default='sent', max_length=100, null=True),
        ),
    ]
