# Generated by Django 3.1.7 on 2021-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210307_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancytag',
            name='vacancies',
        ),
        migrations.AlterField(
            model_name='employer',
            name='links',
            field=models.JSONField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CvTag',
        ),
        migrations.DeleteModel(
            name='VacancyTag',
        ),
        migrations.AddField(
            model_name='cv',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
