# Generated by Django 3.1.7 on 2021-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210307_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cv',
        ),
        migrations.AddField(
            model_name='cv',
            name='portfolio',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='about',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_type',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_type',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
