# Generated by Django 3.1.7 on 2021-04-05 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210402_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvresponse',
            name='init',
            field=models.CharField(default='employer', max_length=50),
        ),
        migrations.AddField(
            model_name='vacancyresponse',
            name='init',
            field=models.CharField(default='worker', max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 21, 37, 20, 745177), null=True),
        ),
        migrations.AlterField(
            model_name='cvresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 21, 37, 20, 752158), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 21, 37, 20, 747171), null=True),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 21, 37, 20, 750163), null=True),
        ),
    ]
