# Generated by Django 3.1.7 on 2021-04-05 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210402_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvresponse',
            old_name='cv_response',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='vacancyresponse',
            old_name='worker_cv',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='vacancyresponse',
            old_name='vacancy_response',
            new_name='vacancy',
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 22, 5, 30, 940415), null=True),
        ),
        migrations.AlterField(
            model_name='cvresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 22, 5, 30, 946400), null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 22, 5, 30, 943408), null=True),
        ),
        migrations.AlterField(
            model_name='vacancyresponse',
            name='date_response',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 22, 5, 30, 946400), null=True),
        ),
    ]
