# Generated by Django 3.1.7 on 2021-03-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210310_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='links',
            field=models.JSONField(blank=True, default={}, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='mailing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.JSONField(blank=True, default={}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_background',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='about',
            field=models.JSONField(blank=True, default={}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='bg_header_color',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='leading',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trailing',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_type',
            field=models.JSONField(blank=True, default={}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.JSONField(blank=True, default={}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.JSONField(blank=True, default={}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='language',
            field=models.JSONField(blank=True, default={}, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='mailing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.JSONField(blank=True, default={}, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile_background',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='social_links',
            field=models.JSONField(blank=True, default={}, max_length=1000, null=True),
        ),
    ]
