# Generated by Django 3.1.7 on 2021-03-10 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210310_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 12, 0, 43, 857833, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 12, 0, 43, 859825, tzinfo=utc)),
        ),
    ]
