# Generated by Django 3.1.7 on 2021-03-10 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210310_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 5, 24, 42327, tzinfo=utc), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default=datetime.datetime(2021, 3, 10, 12, 5, 24, 44840, tzinfo=utc), max_length=200, null=True),
        ),
    ]
