# Generated by Django 3.1.7 on 2021-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210310_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:07:17.037386', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:07:17.040350', max_length=200, null=True),
        ),
    ]
