# Generated by Django 3.1.7 on 2021-03-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210310_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='portfolio',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:20:14.450805', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='work_type',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='links',
            field=models.JSONField(blank=True, default=list, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.JSONField(blank=True, default=list, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='about',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:20:14.452799', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_type',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='language',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.JSONField(blank=True, default=list, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='social_links',
            field=models.JSONField(blank=True, default=list, max_length=1000, null=True),
        ),
    ]
