# Generated by Django 3.1.7 on 2021-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210310_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:38:10.758993', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.JSONField(blank=True, default='empty', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:38:10.761985', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='profile_link',
            field=models.CharField(blank=True, default='empty', max_length=500, null=True),
        ),
    ]
