# Generated by Django 3.1.7 on 2021-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210310_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:39:00.202272', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.JSONField(blank=True, default=list, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_link',
            field=models.CharField(blank=True, default='empty', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 15:39:00.205265', max_length=200, null=True),
        ),
    ]
