# Generated by Django 3.1.7 on 2021-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210310_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 16:54:50.593362', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='salary',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 16:54:50.596355', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
