# Generated by Django 3.1.7 on 2021-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210310_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='about',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 17:22:46.886750', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-10 17:22:46.888771', max_length=200, null=True),
        ),
    ]
