# Generated by Django 3.1.7 on 2021-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210317_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:16:46.191855', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:16:46.193866', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.JSONField(blank=True, default=list, max_length=600, null=True),
        ),
    ]
