# Generated by Django 3.1.7 on 2021-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210317_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:29:42.157843', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:29:42.161858', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.JSONField(blank=True, default=list, max_length=500, null=True),
        ),
    ]
