# Generated by Django 3.1.7 on 2021-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210317_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.AlterField(
            model_name='cv',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:49:40.176259', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='pub_date',
            field=models.CharField(blank=True, default='2021-03-17 15:49:40.178255', max_length=200, null=True),
        ),
    ]
